language: node_js
node_js:
  - 'node'
  - 'lts/*'
cache: npm
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - curl -s https://codecov.io/bash | bash
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

jobs:
  include:
    - stage: npm release
      node_js: 'lts/*'
      deploy:
        provider: npm
        email: $NPM_MAIL
        api_key: $NPM_TOKEN
        on: deploy-npm-release
