version: 2
jobs:
  node-latest: &test
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          command: npm test
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'

  node-lts:
    <<: *test
    docker:
      - image: circleci/node:lts

workflows:
  version: 2
  'test':
    jobs:
      - node-latest
      - node-lts
